use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A single recorded step in a technique's reasoning trajectory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrajectoryStep {
    /// Zero-based index of this step within the run.
    pub index: usize,
    /// Semantic role of this step.
    #[serde(rename = "type")]
    pub step_type: StepType,
    /// Human-readable content of the step (thought text, tool output, etc.).
    pub content: String,
    /// ISO-8601 timestamp string recorded when the step was emitted.
    pub timestamp: String,
    /// Arbitrary extra data attached by the technique (tool name, scores, …).
    #[serde(default)]
    pub metadata: HashMap<String, serde_json::Value>,
}

/// The semantic role a [`TrajectoryStep`] plays in the reasoning loop.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum StepType {
    Thought,
    Action,
    Observation,
    Reflection,
}

/// The final result returned by every technique implementation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunResult {
    /// Name of the technique that produced this result (e.g. `"react"`).
    pub technique: String,
    /// The final answer or output generated by the technique.
    pub answer: String,
    /// Full reasoning trajectory recorded during the run.
    pub trajectory: Vec<TrajectoryStep>,
    /// Total number of LLM completions made during the run.
    pub llm_calls: usize,
    /// Wall-clock duration of the run in milliseconds.
    pub duration_ms: u64,
    /// `true` when the technique reached a final answer without fatal error.
    pub success: bool,
    /// Present only when `success` is `false`; describes the failure.
    pub error: Option<String>,
}

impl RunResult {
    /// Construct a successful [`RunResult`].
    pub fn success(
        technique: impl Into<String>,
        answer: impl Into<String>,
        trajectory: Vec<TrajectoryStep>,
        llm_calls: usize,
        duration_ms: u64,
    ) -> Self {
        Self {
            technique: technique.into(),
            answer: answer.into(),
            trajectory,
            llm_calls,
            duration_ms,
            success: true,
            error: None,
        }
    }

    /// Construct a failed [`RunResult`].
    pub fn failure(
        technique: impl Into<String>,
        error: impl Into<String>,
        trajectory: Vec<TrajectoryStep>,
        duration_ms: u64,
    ) -> Self {
        Self {
            technique: technique.into(),
            answer: String::new(),
            trajectory,
            llm_calls: 0,
            duration_ms,
            success: false,
            error: Some(error.into()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fake_step(index: usize) -> TrajectoryStep {
        TrajectoryStep {
            index,
            step_type: StepType::Thought,
            content: format!("step {index}"),
            timestamp: "2026-01-01T00:00:00Z".to_string(),
            metadata: HashMap::new(),
        }
    }

    #[test]
    fn success_result_fields() {
        let r = RunResult::success("react", "42", vec![fake_step(0)], 3, 1500);
        assert!(r.success);
        assert_eq!(r.technique, "react");
        assert_eq!(r.answer, "42");
        assert_eq!(r.llm_calls, 3);
        assert_eq!(r.duration_ms, 1500);
        assert!(r.error.is_none());
        assert_eq!(r.trajectory.len(), 1);
    }

    #[test]
    fn failure_result_fields() {
        let r = RunResult::failure("react", "timeout", vec![], 500);
        assert!(!r.success);
        assert_eq!(r.answer, "");
        assert_eq!(r.llm_calls, 0);
        assert_eq!(r.error.as_deref(), Some("timeout"));
    }

    #[test]
    fn step_type_serde_roundtrip() {
        let step = fake_step(0);
        let json = serde_json::to_string(&step).unwrap();
        let decoded: TrajectoryStep = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.index, 0);
        assert!(json.contains("\"thought\""));
    }

    #[test]
    fn run_result_serde_roundtrip() {
        let r = RunResult::success("tot", "answer", vec![fake_step(0)], 5, 2000);
        let json = serde_json::to_string(&r).unwrap();
        let decoded: RunResult = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.technique, "tot");
        assert!(decoded.success);
    }
}
